---
kind: pipeline
name: default

steps:
  - name: rootfs
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - sh dev/vm/build_rootfs.sh
  - name: build_server
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker build -t registry.dewardt.uk/doxa/server:drone-build-"$DRONE_BUILD_NUMBER" -f aisoc/deploy/Dockerfile.server .
    depends_on:
      - rootfs
  - name: build_web
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker build -t registry.dewardt.uk/doxa/web:drone-build-"$DRONE_BUILD_NUMBER" -f aisoc/deploy/Dockerfile.web .
  - name: publish
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    environment:
      DOCKER_PASSWORD:
            from_secret: DOCKER_PASSWORD
    commands:
      - echo $DOCKER_PASSWORD | docker login https://registry.dewardt.uk --username doxa --password-stdin
      - docker tag registry.dewardt.uk/doxa/server:drone-build-"$DRONE_BUILD_NUMBER" registry.dewardt.uk/doxa/server:production
      - docker tag registry.dewardt.uk/doxa/web:drone-build-"$DRONE_BUILD_NUMBER" registry.dewardt.uk/doxa/web:production
      - docker push registry.dewardt.uk/doxa/server:production
      - docker push registry.dewardt.uk/doxa/web:production
    when:
      target:
      - production
    depends_on:
      - build_server
      - build_web

trigger:
  event:
    - push
    - pull_request

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock

---
kind: pipeline
name: server_check

steps:
  - name: clippy
    image: rust:latest
    commands:
      - rustup component add clippy
      - cargo clippy --workspace

trigger:
  event:
    - push
    - pull_request

---
kind: pipeline
name: client_check

steps:
  - name: install packages and lint
    image: node:lts
    commands:
      - cd aisoc_ui
      - npm install
      - npm run build

trigger:
  event:
    - push
    - pull_request
