[package]
name = "doxa_adm"
version = "0.1.0"
edition = "2018"

[dependencies]
doxa_db = { path = "../doxa_db" }
clap = { version = "3.0.0-rc.0", features = ["derive"] }
dotenv = "0.15.0"
parse_duration = "2.1.1"
chrono-humanize = "0.2.1"
chrono = "0.4.19"
