FROM node:lts AS app

WORKDIR app
COPY aisoc/client/package*.json ./


RUN npm ci

COPY aisoc/client .

# TODO: remove DISABLE_ESLINT_PLUGIN in future once the frontend is free of warnings
RUN DISABLE_ESLINT_PLUGIN=true npm run build

FROM nginx:stable

COPY aisoc/deploy/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=app /app/build /usr/share/nginx/html

EXPOSE 80
