FROM node:lts AS app

WORKDIR app
COPY aisoc/client/package*.json ./


RUN npm ci

COPY aisoc/client .


ARG multiple_competitions
ARG default_competition
ARG title
ARG domain

ENV REACT_APP_DEFAULT_COMPETITION=$default_competition
ENV REACT_APP_MULTIPLE_COMPETITIONS=$multiple_competitions
ENV REACT_APP_TITLE=$title
ENV REACT_APP_DOMAIN=$domain

RUN echo $REACT_APP_DEFAULT_COMPETITION
RUN echo $REACT_APP_MULTIPLE_COMPETITIONS
# TODO: remove DISABLE_ESLINT_PLUGIN in future once the frontend is free of warnings
RUN DISABLE_ESLINT_PLUGIN=true npm run build

FROM nginx:stable

COPY aisoc/deploy/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=app /app/build /usr/share/nginx/html

EXPOSE 80
