DROP TABLE IF EXISTS leaderboard;
DROP TABLE IF EXISTS game_participants;
DROP TABLE IF EXISTS game_events;
DROP TABLE IF EXISTS games;
DROP TABLE IF EXISTS agents;
DROP TABLE IF EXISTS enrollment;
DROP TABLE IF EXISTS competitions;
DROP TABLE IF EXISTS users;
